### ISSUE TITLE
Add License

### ISSUE THREAD

**Issue by sudodoki** [vseloved/prj-algo#59]
Hi!
This repo is awesome as source of related links and keywords to investigate different topics. What is the license for this? Because by default no license = closed license. Maybe [cc/by-nc-sa/3.0](https://creativecommons.org/licenses/by-nc-sa/3.0/) or similar?

**Comment by vseloved** [comment]
Yes, this one is ok. But only for my work, not for your homeworks - that's your property :)

**Comment by vseloved** [comment]
https://github.com/vseloved/prj-algo/commit/cf645b837a85fbb574927d09858b5a4eede420de#diff-04c6e90faac2675aa89e2176d2eec7d8R5
